const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Deliciously buttery and fluffy with golden, crisp edges and an irresistible buttermilk flavour. `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Perfect blend of veggies with cheese and fries. `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Milo blended with banana & mint chocolate chip ice cream, drizzled with melted chocolate & topped with more ice cream & Milo`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Sourdough bread dipped in a rich egg batter, served golden brown, with sliced toasted almonds and dusted withcinnamon sugar. Served with whipped butter and hot syrup. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `This juicy egg topped bacon cheeseburger is gooey, decadent, and dripping with flavor!`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Oreo milkshake is everything you want on a hot summer day!! Its thick, creamy, delicious and satisfies all the sweet cravings!!`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Take your grilled cheese sandwich to a place it's never been before with crispy bacon and tangy tomatoes and five—yes, five!—types of cheese. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `The very classic and traditional Burger served with sweet potatoes fries and a coke.`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `The flavors of chocolate and coffee were made to go together. And humans were made to drink milkshakes. We took these two undeniable truths and created our famous Jamocha Shake. It's a frosty, chocolate-y, coffee-y treat.`,
  },
];
export default menu;
